add asynchronous task management
hugegraph/hugegraph-hubble pull request #245
Opened 2020-09-24 01:32 UTC by shzcore

2020-09-24 07:33 UTC, javeme requested changes

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +                                          required = false,
align with name

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +                                          int pageNo,
align with @RequestParam

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +                        Constant.COMMON_NAME_PATTERN
align with newEntity

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/LoadTaskController.java
> +                    jobEntity);
align with "job-manager

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/LoadTaskController.java
> +                    jobEntity);
ditto

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/LoadTaskController.java
> +                    jobEntity);
ditto

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/LoadTaskController.java
> +                    jobEntity);
ditto

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/query/GremlinQueryController.java
> +        history = new ExecuteHistory(null, connId,0L, ExecuteType.GREMLIN,
missing space

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/enums/AsyncTaskStatus.java
> +}
add empty line

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/enums/FileMappingStatus.java
> +}
ditto

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/enums/JobManagerStatus.java
> +}
ditto

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/AsyncTaskService.java
> +}
ditto

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/AsyncTaskService.java
> +        Iterator<Task> nodes = list.iterator();
Iterator<Task> tasks

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/AsyncTaskService.java
> +            Task node = nodes.next();
Task task

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/AsyncTaskService.java
> +               !(content.equals(node.id() + "") || node.name().contains(content))) {
don't need to `node.id() + ""`

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/OltpAlgoService.java
> +                .type(GremlinResult.Type.PATH)
align with .builder

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/OltpAlgoService.java
> +    private TableView BuildPathTableView(Path result) {
Build => build

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/OltpAlgoService.java
> +     * TODO
improve it

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/OltpAlgoService.java
> +    private GraphView BuildPathGraphView(Path result) {
ditto

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/query/ExecuteHistoryService.java
> +
empty line

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/resources/database/schema.sql
> +    `file_status` TINYINT NOT NULL DEFAULT 0 COMMENT '文件上传状态',
remove COMMENT  or update Chinese to English

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/resources/database/schema.sql
> +    `create_time` DATETIME(6) NOT NULL COMMENT '创建时间',
ditto

2020-09-24 07:33 UTC, javeme commented on hubble-be/src/main/resources/database/schema.sql
> +    `create_time`  DATETIME(6)  NOT NULL COMMENT '创建时间',
ditto

2020-09-24 08:23 UTC, Linary requested changes

2020-09-24 08:42 UTC, Linary requested changes

2020-09-24 08:42 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/FileUploadController.java
> +        String dirPath = Paths.get(location, CONN_PREIFX + connId + jobId, fileName)
建议不要用connId + jobId形成路径，多加一层目录，job-${jobId}

2020-09-25 04:03 UTC, Linary requested changes

2020-09-25 04:03 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +                     Constant.COMMON_REMARK_PATTERN.matcher(entity.getJobRemarks()).matches(),
如果备注字符串为空，这里的正则匹配会出错。entity.getJobRemarks() != null改成!StringUtils.isEmpty(entity.getJobRemarks())

2020-09-25 04:03 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +                    "job.manager.job-remarks.unmatch-regex");
引号对齐，与括号后的第一个字母对齐

2020-09-25 08:54 UTC, Linary requested changes

2020-09-25 08:54 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/algorithm/ShortPath.java
> +public class ShortPath {
ShortPath -> ShortestPath

2020-09-25 08:54 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/algorithm/AsyncTaskResult.java
> +package com.baidu.hugegraph.entity.algorithm;
Add copyright at file header

2020-09-25 08:54 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/enums/JobManagerStatus.java
> +    IMPORTING(4);
IMPORTING -> LOADING

2020-09-25 08:54 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/load/JobManagerReasonResult.java
> +package com.baidu.hugegraph.entity.load;
加上copy right，其他新文件也检查一下

2020-09-25 08:54 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/load/LoadTask.java
> +    @TableField("`load_status`")
删除`

2020-09-25 08:54 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/query/ExecuteHistory.java
> +import javax.ws.rs.DefaultValue;
删掉

2020-09-25 08:54 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/OltpAlgoService.java
> +    public GremlinResult shortPath(int connId, ShortPath body) {
shortestPath

2020-09-25 09:05 UTC, shzcore commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/enums/JobManagerStatus.java
> +    IMPORTING(4);
前端也需要调整，本期暂不调整

2020-09-25 12:07 UTC, javeme requested changes

2020-09-25 12:07 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/LoadTaskController.java
> +                    jobEntity);
align with "job-manager

2020-09-25 12:07 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/query/GremlinQueryController.java
> +                                 @RequestBody GremlinQuery query) {
align

2020-09-25 12:07 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/entity/algorithm/ShortestPath.java
> +
remove empty line

2020-09-25 12:07 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/mapper/load/JobManagerMapper.java
> +    @Select("SELECT ISNULL(SUM(f.total_size),0) as total_size , ISNULL(SUM(l.duration),0) " +
remove space from "total_size ,"

2020-09-25 12:07 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/load/JobManagerService.java
> +                                p);
align with "job-manager

2020-09-25 12:07 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/query/ExecuteHistoryService.java
> +
remove empty line

2020-09-25 12:07 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/query/GremlinQueryService.java
> +        // Scan data, vote the result type
improve

2020-09-25 12:07 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/query/GremlinQueryService.java
> +
improve

2020-09-27 07:15 UTC, javeme requested changes

2020-09-27 07:15 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/load/JobManagerService.java
> +                            p.getUpdateTime() : HubbleUtil.nowDate();
align with "(p"

2020-09-27 07:15 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/query/ExecuteHistoryService.java
> +                    long endDate = task.updateTime() > 0 ? task.updateTime() : new Date().getTime();
replace all the "new Date()" to now()

2020-09-28 06:30 UTC, Linary requested changes

2020-09-28 06:30 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +        tasks.forEach((p) -> {
p -> task, 并且可以去掉括号。

2020-09-28 06:30 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +            String reason = this.taskService.readLoadFailedReason(mapping);
只有status为FAILED的task才能获取reason

2020-09-28 06:30 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +    private static final int LIMIT = 500;
静态变量与非静态变量之间加一个空行

2020-09-28 06:30 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +        return Response.builder().status(200).data(reasonResults).build();
200 -> Constant.STATUS_OK

2020-09-28 06:30 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +    public Response reason(@PathVariable("connId") int jobId,
jobId -> connId

2020-09-28 07:11 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/FileUploadController.java
> +        String dirPath = Paths.get(location, path, fileName).toString();
rename dirPath to filePath

2020-09-28 07:11 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/GraphConnectionController.java
> +                  (!StringUtils.isEmpty(newEntity.getUsername()) &&
remove the first space

2020-09-28 07:11 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/GraphConnectionController.java
> +                  "graph-connection.username-or-password.must-be-same-status");
remove the first space

2020-09-28 07:11 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/load/JobManagerController.java
> +        return Response.builder().status(Constant.STATUS_OK).data(reasonResults).build();
exceed 80 chars

2020-09-28 11:17 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/AsyncTaskService.java
> +                !(content.equals(task.id() + "") || task.name().contains(content))) {
unnecessary task.id() + ""

2020-09-29 08:28 UTC, Linary requested changes

2020-09-29 08:28 UTC, Linary commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/algorithm/AsyncTaskController.java
> +@RequestMapping(Constant.API_VERSION + "graph-connections/{connId}/algorithm/async-task")
异步任务不应该限定于algorithm下，下一版本记得与前端协商改掉。另外async-task -> async-tasks

2020-09-29 09:25 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/algorithm/AsyncTaskController.java
> +@RequestMapping(Constant.API_VERSION + "graph-connections/{connId}/algorithm/async-task")
可以在当前版本改吗？

2020-09-29 12:49 UTC, shzcore commented on hubble-be/src/main/java/com/baidu/hugegraph/controller/algorithm/AsyncTaskController.java
> +@RequestMapping(Constant.API_VERSION + "graph-connections/{connId}/algorithm/async-task")
已更改

2020-09-29 12:50 UTC, javeme commented on hubble-be/src/main/java/com/baidu/hugegraph/service/algorithm/AsyncTaskService.java
> +                String task_id = String.valueOf(task.id());
rename to taskId

2020-09-29 12:53 UTC, javeme approved these changes

2020-09-29 13:08 UTC, Linary approved these changes

2020-09-29 13:08 UTC, merged