Add check for load parameter
hugegraph/hugegraph-hubble pull request #272
Opened 2020-11-27 08:22 UTC by Linary

2020-11-27 11:06 UTC, javeme requested changes

2020-11-27 11:06 UTC, javeme commented on hubble-be/src/main/resources/i18n/messages_zh_CN.properties
> +load.file-mapping.load-parameter.max-parse-error.illegal=导入参数 'max-parse-errors' 不合法
also use chinese

2020-11-30 03:33 UTC, javeme approved these changes

2020-11-30 04:00 UTC, houzhizhen requested changes

2020-11-30 04:00 UTC, houzhizhen commented on hubble-be/src/main/resources/i18n/messages.properties
> +load.file-mapping.load-parameter.max-parse-error.illegal=The load paramter 'max-parse-errors' is illegal
paramter -> parameter

2020-11-30 04:03 UTC, zhoney approved these changes

2020-11-30 04:07 UTC, houzhizhen approved these changes

2020-11-30 04:11 UTC, merged